### ISSUE TITLE
Bugs in account menu env jump links

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_envbar#35]
Appears to be 2 bugs:

![image](https://cloud.githubusercontent.com/assets/187449/20581432/e53bedfc-b22c-11e6-9ccc-5db7ef34040d.png)

* [x] it looks like the logic might be running twice and so creating double the number of identical env bar items
* [x] there are also empty env items

**Comment by nhoobin** [comment]
This appears to be due to duplicate content in the additionalhtmltopofbody config item. A quick fix is to delete the contents of that item and let the Environment bar regenerate it. It should remove the duplicate.

This would need to be applied to the production server as each refresh of the db will regress the issue.

Regarding the empty items, they are actually separators that have been css/themed out of existence. An extra configuration item has been applied which allows selecting the separator class which will be used. This could also be any new css that is added in the extracss configuration item.

**Comment by nhoobin** [comment]
This duplication will be fixed with merging issue #32 'The additionalhtmltopofbody is being actually set with content when editing'.
